### ISSUE TITLE
Send modifier keys to the attached pane via .send_keys()

### ISSUE THREAD

**Issue by RPiAwesomeness** [tony/libtmux#13]
I really like the look of this project. However, for something that I need to do, I need to be able to send a modifier key, <kbd>Ctrl</kbd> to be exact.

I've tried a few different things and I'll continue looking around for a solution, but I figured I would post an issue here in case this is not currently possible.

**Comment by tony** [comment]
Would ``C-key`` work?

For Ctrl-a,  do ``C-a`` or ``^-a``

**Comment by RPiAwesomeness** [comment]
@tony Unfortunately I already tried that and it just gives an error, both in zsh and and in bash:
![selection_004](https://cloud.githubusercontent.com/assets/11481499/17967447/3c9d29c4-6a95-11e6-8834-fd9638310e82.png)

**Comment by tony** [comment]
I'm considering making ``enter=False`` and ``suppress_history=False`` by default.

Give this a shot, it worked for me:

```python
pane.libtmux.Server().sessions[0].attached_window.panes[0].
```

Quick snippet:

```python
libtmux.Server().sessions[0].attached_window.panes[2].send_keys('C-c', enter=False, suppress_history=False)
```

**Comment by RPiAwesomeness** [comment]
@tony Sorry for not responding soon, I was gone and didn't take any machines with me. I had to tweak your snippets to work, but running 

```python
libtmux.Server().sessions[0].attached_window.panes[0].send_keys('C-c', enter=False, suppress_history=False)
```

did work, it did seem to send Ctrl-C!
