### ISSUE TITLE
How to send a key to the pane?

### ISSUE THREAD

**Issue by niya3** [tony/libtmux#15]
Works from terminal:
`tmux send-key -t 0 Enter`
->

```
user@host$
user@host$
```

Doesn't work in libtmux:

```
>>> import libtmux
>>> pane = libtmux.Server().get_by_id('$1').attached_pane
>>> pane
Pane(%5 Window(@4 2:a, Session($1 foo)))
>>> pane.send_keys('Enter')
```

->

```
user@host$  Enter
Enter: command not found
```

**up.** oh, #13 -_-

**Comment by tony** [comment]
https://libtmux.readthedocs.io/api.html#libtmux.Pane.send_keys

What keys are you trying to send?

```python
pane.send_keys('')
```

It automatically sends enter for you, unless you do ``enter=False``:

```python
pane.send_keys('echo "Hi"', enter=False)
```

**Comment by niya3** [comment]
I'm trying to send Enter, Up, Down, and other special keys.

man tmux

> tmux allows a command to be bound to most keys, with or without a prefix
>      key.  When specifying keys, most represent themselves (for example ‘A’ to
>      ‘Z’).  Ctrl keys may be prefixed with ‘C-’ or ‘^’, and Alt (meta) with
>      ‘M-’.  In addition, the following special key names are accepted: Up,
>      Down, Left, Right, BSpace, BTab, DC (Delete), End, Enter, Escape, F1 to
>      F20, Home, IC (Insert), NPage/PageDown/PgDn, PPage/PageUp/PgUp, Space,
>      and Tab.

**Comment by tony** [comment]
Does ``pane.send_keys('')`` work to send ``Enter``?

Also, you can try the other keys as well, does ``send_keys('Left', enter=False, suppress_history=False)`` work?
