### ISSUE TITLE
Creating servers

### ISSUE THREAD

**Issue by samvv** [tony/libtmux#17]
Love the work you've put into this!

There one thing bothering me, however, couldn't find it in the docs ... is it currently possible to create a new server? When I do, I get a `no such file or directory`-error pointing to the path of the (supposed socket).

Thanks,
Sam

**Comment by tony** [comment]
Try something like this:

```
>>> import libtmux

>>> s = libtmux.Server(socket_name='test2')

>>> s.new_session('test session')
Session($0 test session)

>>> s.list_sessions()
[Session($0 test session)]
```

**Comment by samvv** [comment]
Great, it works! Thanks!

**Comment by MordorianGuy** [comment]
In my opinion, might it be helpful to specify in the documentation that the real server is not initialised at the Python object initialisation, and you should create a new session to make it come alive?
