### ISSUE TITLE
Cannot start another Virtual Enviroment in tmux (locked to actual python's venv)

### ISSUE THREAD

**Issue by gascarcella** [tony/libtmux#39]
Hello. I need to run this on Django. My django has his own virtual enviroment. I'm trying to start another python project (with his own virtual enviroment)in a tmux pane.

I've tried to run source venv/bin/activate inside pane, but seems like it's locked to actual running python virtual enviroment.

This is my code:
`def startproc(path):
    tmux = libtmux.Server()
    session = tmux.new_session('myproc', True, False, path)
    pane = session.attached_pane
    cmd = pane.send_keys('source ../venv/bin/activate')
   cmd = pane.send_keys('python __main__.py start')
return cmd`

Paths are OK. 
When i connect to the tmux via terminal, i see an import error, since virtual enviroment isn't loaded.
If i try the exact same commands in tmux without python, everythings works ok.

I any way to fix this?

Thank you!

**Comment by tony** [comment]
This was closed, were you able to fix it?
