### ISSUE TITLE
Server.has_session() erroneously reports session exists with tmux 2.5

### ISSUE THREAD

**Issue by jlargentaye** [tony/libtmux#67]
tmux from MacPorts (on macOS 10.12.6), recently updated to tmux 2.5.

Tmuxp erroneously reports the session already exists when trying to load the session.

Some light debugging points to libtmux/server.py:Server.has_sessions() does not account for 'tmux has-session' now responds with 'no current session'.

**Comment by jlargentaye** [comment]
After doing a "tmux kill-server", I can't reproduce the issue. It's looks like previously the tmux server had stayed running after the last session finished. 

I'm not immediately finding a way to get it back into that state.

**Comment by jlargentaye** [comment]
Untested fix in pull-request tony/libtmux#68

**Comment by tony** [comment]
https://github.com/tmux/tmux/blob/e802b683ea0ebfa377a5bb8a6b03454c1edbe2d5/cmd-set-environment.c#L76

https://github.com/tmux/tmux/blob/0824850bbce86c395230700cb10c81f162319858/options.c#L639

I can't think of how to recreate it, but that'd be helpful in making a testcase for it.
