### ISSUE TITLE
Would it be better to use `logger` instead of `logging` in `libtmux.common.tmux_cmd` ? 

### ISSUE THREAD

**Issue by geekli** [tony/libtmux#9]
It's use `logging` in function `__init__` of Class `tmux_cmd`
`logging.debug('self.stdout for %s: \n%s' %
                      (' '.join(cmd), self.stdout))`

**Comment by geekli** [comment]
It's print a lot of debug message like:

>  root: DEBUG self.stdout for /usr/bin/tmux send-keys -t %3926  reset:
>  root: DEBUG self.stdout for /usr/bin/tmux send-keys -t %3926 Enter:
> ...

Because it's "root" ,so not easy to closed and not affect others

**Comment by tony** [comment]
@geekli Can you try to make a pull request to try it out?
